#!/usr/bin/env bash
# generate_hashes.sh — Generate expected codehashes for a hardfork.
#
# Compiles contracts and generates expected codehashes for verification.
# Outputs a <hardfork>_expected_hashes.sh file under generated/.
#
# Usage:
#   cd gravity_chain_core_contracts
#   bash scripts/verify_hardfork/generate_hashes.sh <hardfork_name>
#
# Examples:
#   bash scripts/verify_hardfork/generate_hashes.sh gamma
#   bash scripts/verify_hardfork/generate_hashes.sh delta
#
# Requirements: forge, cast, python3

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <hardfork_name>"
    echo "Example: $0 gamma"
    exit 1
fi

HARDFORK_NAME="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source shared libraries
source "${SCRIPT_DIR}/lib/addresses.sh"
source "${SCRIPT_DIR}/lib/stakepool.sh"

# Source hardfork-specific configuration (for SYSTEM_CONTRACTS list)
HARDFORK_CONFIG="${SCRIPT_DIR}/hardforks/${HARDFORK_NAME}.sh"
if [ ! -f "$HARDFORK_CONFIG" ]; then
    echo "❌ Unknown hardfork: ${HARDFORK_NAME}"
    echo "   No config found at: ${HARDFORK_CONFIG}"
    exit 1
fi
source "$HARDFORK_CONFIG"

# Output directory
mkdir -p "${SCRIPT_DIR}/generated"
OUTPUT_FILE="${SCRIPT_DIR}/generated/${HARDFORK_NAME}_expected_hashes.sh"

echo "=== Generating Expected Codehashes for ${HARDFORK_DISPLAY_NAME:-$HARDFORK_NAME} ==="
echo "Repository: ${REPO_ROOT}"
echo ""

# Step 1: Build contracts
echo "Building contracts..."
(cd "$REPO_ROOT" && forge build --quiet)
echo "Build complete."
echo ""

# Step 2: Generate hashes for system contracts
echo "Computing codehashes for ${#SYSTEM_CONTRACTS[@]} system contracts..."
{
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by generate_hashes.sh"
    echo "# Hardfork: ${HARDFORK_NAME}"
    echo "# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Compiler: $(forge --version 2>/dev/null | head -1)"
    echo ""
    echo "# ============================================================================"
    echo "# System Contracts (no immutables — forge inspect output is final)"
    echo "# ============================================================================"

    for entry in "${SYSTEM_CONTRACTS[@]}"; do
        name="${entry%%:*}"
        addr="${entry#*:}"
        bytecode=$(cd "$REPO_ROOT" && forge inspect "$name" deployedBytecode 2>/dev/null)
        if [ -z "$bytecode" ] || [ "$bytecode" = "0x" ]; then
            echo "# WARNING: Empty bytecode for $name" >&2
            continue
        fi
        hash=$(cast keccak "$bytecode")
        echo "EXPECTED_HASH_${name}=\"${hash}\""
        echo "  ✅ ${name}: ${hash}" >&2
    done
} > "$OUTPUT_FILE"

echo ""

# Step 3: Generate hash for StakePool (if applicable)
if [ "${VERIFY_STAKEPOOL:-false}" = true ]; then
    echo "Computing StakePool codehash (patching FACTORY immutable)..."
    STAKEPOOL_CODEHASH=$(generate_stakepool_hash "$REPO_ROOT")

    if [ -z "$STAKEPOOL_CODEHASH" ]; then
        echo "ERROR: Failed to compute StakePool bytecode" >&2
        exit 1
    fi
    echo "  ✅ StakePool: ${STAKEPOOL_CODEHASH}"

    {
        echo ""
        echo "# ============================================================================"
        echo "# StakePool (has FACTORY immutable — patched with Staking address)"
        echo "# ============================================================================"
        echo "EXPECTED_HASH_StakePool=\"${STAKEPOOL_CODEHASH}\""
        echo ""
        echo "# Immutable details:"
        echo "#   FACTORY = Staking address = 0x00000000000000000000000000000001625F2000"
    } >> "$OUTPUT_FILE"
fi

echo ""
echo "=== Done! Output written to: ${OUTPUT_FILE} ==="
echo ""
echo "To verify: bash scripts/verify_hardfork/verify.sh ${HARDFORK_NAME} <RPC_URL>"
