#!/usr/bin/env bash
# generate_expected_hashes.sh
#
# Compiles contracts and generates expected codehashes for gamma hardfork verification.
# Outputs an expected_hashes.sh file that can be sourced by verify_gamma.sh.
#
# Usage: cd gravity_chain_core_contracts && bash scripts/verify_gamma/generate_expected_hashes.sh
#
# Requirements: forge, cast, python3

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/expected_hashes.sh"

source "${SCRIPT_DIR}/addresses.sh"

echo "=== Generating Expected Codehashes for Gamma Hardfork ==="
echo "Repository: ${REPO_ROOT}"
echo ""

# Step 1: Build contracts
echo "Building contracts..."
(cd "$REPO_ROOT" && forge build --quiet)
echo "Build complete."
echo ""

# Step 2: Generate hashes for system contracts (no immutables)
echo "Computing codehashes for 11 system contracts..."
{
    echo "#!/usr/bin/env bash"
    echo "# Auto-generated by generate_expected_hashes.sh"
    echo "# Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# Compiler: $(forge --version 2>/dev/null | head -1)"
    echo ""
    echo "# ============================================================================"
    echo "# System Contracts (no immutables — forge inspect output is final)"
    echo "# ============================================================================"

    for entry in "${SYSTEM_CONTRACTS[@]}"; do
        name="${entry%%:*}"
        addr="${entry#*:}"
        bytecode=$(cd "$REPO_ROOT" && forge inspect "$name" deployedBytecode 2>/dev/null)
        if [ -z "$bytecode" ] || [ "$bytecode" = "0x" ]; then
            echo "# WARNING: Empty bytecode for $name" >&2
            continue
        fi
        hash=$(cast keccak "$bytecode")
        echo "EXPECTED_HASH_${name}=\"${hash}\""
        echo "  ✅ ${name}: ${hash}" >&2
    done

    echo ""
    echo "# ============================================================================"
    echo "# StakePool (has FACTORY immutable — patched with Staking address)"
    echo "# ============================================================================"
} > "$OUTPUT_FILE"

echo ""

# Step 3: Generate hash for StakePool (patch FACTORY immutable)
echo "Computing StakePool codehash (patching FACTORY immutable)..."

STAKEPOOL_HASH=$(cd "$REPO_ROOT" && python3 -c "
import subprocess, json, sys

# Get template bytecode
result = subprocess.run(['forge', 'inspect', 'StakePool', 'deployedBytecode'],
                        capture_output=True, text=True)
bytecode_hex = result.stdout.strip()
if bytecode_hex.startswith('0x'):
    bytecode_hex = bytecode_hex[2:]

# Get immutable references from build artifact
with open('out/StakePool.sol/StakePool.json') as f:
    artifact = json.load(f)
imm_refs = artifact.get('deployedBytecode', {}).get('immutableReferences', {})

# There should be exactly one immutable (FACTORY) with 2 references
all_refs = []
for ast_id, refs in imm_refs.items():
    for ref in refs:
        all_refs.append((ref['start'], ref['length']))

if len(all_refs) != 2:
    print(f'ERROR: Expected 2 immutable references, got {len(all_refs)}', file=sys.stderr)
    sys.exit(1)

# Patch with FACTORY = Staking system address
factory_hex = '00000000000000000000000000000000000000000000000000000001625F2000'
patched = bytearray(bytes.fromhex(bytecode_hex))
for (start, length) in all_refs:
    assert length == 32, f'Expected 32-byte immutable, got {length}'
    patched[start:start+32] = bytes.fromhex(factory_hex)

# Output patched bytecode as 0x-prefixed hex
print('0x' + patched.hex())
")

if [ -z "$STAKEPOOL_HASH" ]; then
    echo "ERROR: Failed to compute StakePool bytecode" >&2
    exit 1
fi

STAKEPOOL_CODEHASH=$(cast keccak "$STAKEPOOL_HASH")
echo "  ✅ StakePool: ${STAKEPOOL_CODEHASH}"

{
    echo "EXPECTED_HASH_StakePool=\"${STAKEPOOL_CODEHASH}\""
    echo ""
    echo "# Immutable details:"
    echo "#   FACTORY = Staking address = 0x0000000000000000000000000001625F2000"
} >> "$OUTPUT_FILE"

echo ""
echo "=== Done! Output written to: ${OUTPUT_FILE} ==="
echo ""
echo "To use: source ${OUTPUT_FILE}"
